#!/usr/bin/env python

import math
import os
import sys

if len(sys.argv) < 2:
    print("ERROR: Needs data file argument")
    exit(1)

f = sys.argv[1]
if not os.path.isfile(f):
    print("ERROR: " + f + " is not a file")
    exit(1)

sumx = 0.0
sumy = 0.0
sumxy = 0.0
sumx2 = 0.0
sumy2 = 0.0
n = 0
with open(f) as f_:
    first_line = True
    for line in f_:
        if first_line:
            first_line = False
            continue
        n = n + 1
        sl = line.split(',')
        x = float(sl[0])
        y = float(sl[1])
        sumx += x
        sumx2 += x ** 2
        sumy += y
        sumy2 += y ** 2
        sumxy += x * y

r = (n * sumxy - sumx * sumy) /\
    math.sqrt( (n * sumx2  - sumx ** 2) * (n * sumy2 - sumy ** 2) )

print("Data processing summary: " + sys.argv[1])
print(str(n) + " data points")
print("Correlation: {:6.4f}".format(r))
